{
 "title": "JMSS",
 "time": { "from": "2019-12-30T18:11:21.314Z", "to": "2019-12-30T18:11:53.039Z" },
 "panels": [
  {
   "title": "Restarts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "operations_count_total{type=\"restart\"}"
    }
   ]
  },
  {
   "title": "Initial Clauses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "clauses_count_total{type=\"initial\"}"
    }
   ]
  },
  {
   "title": "Learned Clauses",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "clauses_count_total{type=\"learned\"}"
    }
   ]
  },
  {
   "title": "Operations total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 2 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "operations_count_total", "legendFormat": "{{type}}" }
   ]
  },
  {
   "title": "Operations Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total[1m])",
     "legendFormat": "{{type}} rate"
    }
   ]
  },
  {
   "title": "Decide",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"decide\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"decide\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Unit",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"unit\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"unit\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Conflict",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"conflict\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"conflict\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Backtrack",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"backtrack\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"backtrack\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Backjump",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"backjump\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"backjump\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Explain",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"explain\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"explain\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Learn",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"learn\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"learn\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Forget",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"forget\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"forget\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Restart",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(operations_count_total{type=\"restart\"}[1m])",
     "legendFormat": "{{type}} rate"
    },
    {
     "expr": "operations_count_total{type=\"restart\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}