name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8,11,17,21,24 ]
    name: Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Compile sources
      run: ./build_prod.sh
    - name: Compile tests
      run: ./build_test.sh

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8,11,17,21,24 ]
    name: Java ${{ matrix.java }} compile
    steps:
    - uses: actions/checkout@v2
    - name: Set up java
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - run: ./build_prod.sh
    - run: ./build_test.sh
    - run: ./run_tests.sh
